### ISSUE TITLE
哈哈 这个好像我知道

### ISSUE THREAD

**Issue by JayJay1024** [Dappub/DAPPDevNotes#2]
[https://github.com/Dappub/DAPPDevNotes/blob/master/DAPP%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0-EOS-20180705.md:](https://github.com/Dappub/DAPPDevNotes/blob/master/DAPP%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0-EOS-20180705.md)
`erase`了`bet_itr`之后，`bet_itr`就不能`++`了

**Comment by thbourlove** [comment]
soga，赞 👍
